name: build

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Compile cython files
      run: |
        pip install cython --install-option="--no-cython-compile"
        cython http_router/router.pyx
        cython http_router/routes.pyx

    - name: Build wheels (non-linux)
      run: python setup.py bdist_wheel

    - name: Test wheels
      if: |
        !startsWith(matrix.os, 'windows')
      run: pip install --pre http_router -f "file:///${GITHUB_WORKSPACE}/dist"

    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
