# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop, feature/**]

jobs:

  cythonize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Cythonize the package
      run: |
        pip install cython --install-option="--no-cython-compile"
        cython http_router/router.pyx
        cython http_router/routes.pyx

    - uses: actions/upload-artifact@v2
      with:
        name: http_router
        path: http_router/*.c

  tests:
    runs-on: ubuntu-latest
    needs: cythonize
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy-3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - uses: actions/download-artifact@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v2.1.5
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.cfg') }}
  
    - name: Compile cython files
      run: python setup.py build_ext --inplace
      if: matrix.python-version != 'pypy-3.7'

    - name: Setup requirements
      run: pip install .[tests]

    - name: Check typing
      run: mypy http_router
      if: matrix.python-version != 'pypy-3.7'

    - name: Test with pytest
      run: pytest tests.py
